import type { Metadata } from "next";
import Navbar from "@/app/components/Navbar";
import "./globals.css";
import Footer from "@/app/components/footer";

export const metadata: Metadata = {
  title: "Hero-App",
  description: "Generated by Fahim with Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
