import type { Metadata } from "next";
import Navbar from "@/app/components/Navbar";
import "./globals.css";
import Footer from "@/app/components/footer";
import { AppProvider } from "./context/appContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Hero-App",
  description: "Generated by Fahim with Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className="min-h-screen flex flex-col">
        <AppProvider>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
          <ToastContainer position="top-right" autoClose={2000} />
        </AppProvider>
      </body>
    </html>
  );
}
